server:
  port: 8080
  mode: release # debug 或 release

database:
  driver: mysql
  dsn: root:123456@tcp(10.147.17.1:3306)/homebox?charset=utf8mb4&parseTime=True&loc=Local

jwt:
  secret: "homebox_secret_key_2026" # 用于签名的密钥
  expire_hours: 168